version: '2.2'
services:
  hola:
    build:
      context: ./
      dockerfile: Dockerfile-build
    ports:
      - 8080
    scale: 3
  # Agent container
  datadog:
    image: datadog/agent:latest
    links:
     - hola
    environment:
     - DD_API_KEY=<Insert Your Key Here>
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/mounts:/host/proc/mounts:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

