FROM maven:3.5.2-alpine
LABEL "com.datadoghq.ad.check_names"='["http_check"]'
# LABEL "com.datadoghq.ad.check.id"='["hola"]'  ## Alternate Container Identifier https://docs.datadoghq.com/agent/autodiscovery/#alternate-container-identifier-labels
LABEL "com.datadoghq.ad.init_configs"='[{}]'
LABEL "com.datadoghq.ad.instances"='[{"name": "hola", "url": "http://%%host%%:8080"}]'

WORKDIR /usr/src/java-code
COPY . /usr/src/java-code/
RUN mvn package

WORKDIR /usr/src/java-app
RUN cp /usr/src/java-code/target/*.jar ./app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
